### ISSUE TITLE
Running update with go 1.11 installed, autocompletion no longer works in vim editing go files

### ISSUE THREAD

**Issue by BooleanCat** [luan/vimfiles#126]
After updating go to 1.11 and then running update, I see the following whenever I try to edit a go file in vim: `gocode panicked`.

I found the following in the gocode repo: https://github.com/mdempsky/gocode/issues/48

Seems like it no longer works out of the box with go 1.11. I realise this isn't strictly an issue with luan/vimfiles but I thoght I'd document it here to save others the trouble. Until a root cause for the issue is discovered and fixed, I've found the following hack in my ansible script (to be run after vim-update) patches the issue:

```
  - name: 'patch gocode: fetch'
    git:
      repo: https://github.com/mdempsky/gocode
      dest: ~/go/src/github.com/mdempsky/gocode
      force: yes

  - name: 'patch gocode: build'
    shell: '{{ item }}'
    args:
      chdir: ~/go/src/github.com/mdempsky/gocode
    with_items:
    - 'if [ ! -f go.mod ]; then GO111MODULE=on go mod init; fi'
    - 'GO111MODULE=on go build -o ~/.vim/gobin/gocode github.com/mdempsky/gocode'
```
